(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const u of i.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function c(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(o){if(o.ep)return;o.ep=!0;const i=c(o);fetch(o.href,i)}})();function a(s,e){try{const c=JSON.stringify(e);localStorage.setItem(s,c)}catch(c){console.log(c)}}function k(s){try{const e=localStorage.getItem(s);return e===null?void 0:JSON.parse(e)}catch(e){console.log(e)}}function h(s){try{localStorage.removeItem(s)}catch(e){console.log(e)}}const p=()=>{document.body.classList.add("dark-theme"),a("darkmode","active")},g=()=>{document.body.classList.remove("dark-theme"),h("darkmode")};let f=k("darkmode");f==="active"&&p();document.querySelector(".js-theme-btn").addEventListener("click",()=>{f=k("darkmode"),f!=="active"?p():g()});const r={formEl:document.querySelector(".js-form"),tasksListEl:document.querySelector(".js-list"),textContentOfEmptyList:document.querySelector(".js-empty-item"),clearTasksBtn:document.querySelector(".js-clear-taskts-btn"),tasksQuantity:document.querySelector(".js-quantity"),filters:document.querySelectorAll(".js-filter-btn")};function m(s){const e=s.filter(n=>!n.completed).length,c=e===1?"task":"tasks";r.tasksQuantity.textContent=`${e} ${c} left`}function y(s,e){const c=document.createElement("li");return c.className="list-item",c.id=`task-${e}`,c.innerHTML=`
  <input class="checkbox js-checkbox visually-hidden" type="checkbox" id="${e}"/>
  <label class="checkbox-label" for="${e}">
     <span class="custom-checkbox">
        <svg class="custom-checkbox-icon" width="10px" height="10px">
          <use href=".//img/icons/symbol-defs.svg#icon-icon-check"></use>
        </svg>
     </span>
     <p class="task-text">${s.text}</p>
  </label>
  <button class="delate-btn" id="btn-${e}">
     <svg class="btn-icon">
         <use href="./img/icons/symbol-defs.svg#icon-icon-cross"></use>
     </svg>
  </button>
  `,c}function L(s){r.tasksListEl.innerHTML="",s.length?(r.textContentOfEmptyList.classList.add("is-hidden"),r.clearTasksBtn.disabled=!1):(r.textContentOfEmptyList.classList.remove("is-hidden"),r.clearTasksBtn.disabled=!0),s.forEach((e,c,n)=>{const o=y(e,c);r.tasksListEl.append(o);const i=o.querySelector(".js-checkbox");i.addEventListener("change",u=>{n[c].completed=u.currentTarget.checked,a("tasks",n),d(l),m(n)}),i.checked=e.completed,o.querySelector(`#btn-${c}`).addEventListener("click",()=>{v(n,e.id)})}),m(s)}function d(s){let e=[];switch(s){case"active":{e=t.filter(c=>!c.completed);break}case"completed":{e=t.filter(c=>c.completed);break}default:e=t}L(e)}let t=k("tasks")||[],l="all";t.length&&(r.textContentOfEmptyList.classList.add("is-hidden"),d(l),r.clearTasksBtn.addEventListener("click",()=>{l==="all"?(t=[],a("tasks",t)):l==="active"?(t=t.filter(s=>s.completed),a("tasks",t)):l==="completed"&&(t=t.filter(s=>!s.completed),a("tasks",t)),d(l),m(t),t.length||(r.textContentOfEmptyList.classList.toggle("is-hidden"),r.clearTasksBtn.disabled=!0)}));function b(s){s.preventDefault();const e=r.formEl.elements.task.value.trim();if(e==="")return;const c={id:Date.now(),text:e,completed:!1};t.push(c),d(l),r.textContentOfEmptyList.classList.add("is-hidden"),a("tasks",t),r.clearTasksBtn.addEventListener("click",()=>{l==="all"?(t=[],a("tasks",t)):l==="active"?(t=t.filter(n=>n.completed),a("tasks",t)):l==="completed"&&(t=t.filter(n=>!n.completed),a("tasks",t)),d(l),m(t),t.length||(r.textContentOfEmptyList.classList.toggle("is-hidden"),r.clearTasksBtn.disabled=!0)}),s.currentTarget.reset()}r.formEl.addEventListener("submit",b);function v(s,e){t=s.filter(c=>c.id!==e),a("tasks",t),d(l),m(t),r.tasksListEl.children.length||r.textContentOfEmptyList.classList.remove("is-hidden")}r.filters.forEach(s=>{s.addEventListener("click",e=>{document.querySelector(".js-filter-btn.active").classList.remove("active"),e.target.classList.add("active"),l=e.target.id,d(l)})});
//# sourceMappingURL=index.js.map
