(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();function u(t,e){try{const n=JSON.stringify(e);localStorage.setItem(t,n)}catch(n){console.log(n)}}function g(t){try{const e=localStorage.getItem(t);return e===null?void 0:JSON.parse(e)}catch(e){console.log(e)}}function v(t){try{localStorage.removeItem(t)}catch(e){console.log(e)}}const p=()=>{document.body.classList.add("dark-theme"),u("darkmode","active")},y=()=>{document.body.classList.remove("dark-theme"),v("darkmode")};let m=g("darkmode");m==="active"&&p();document.querySelector(".js-theme-btn").addEventListener("click",()=>{m=g("darkmode"),m!=="active"?p():y()});const s={formEl:document.querySelector(".js-form"),tasksListEl:document.querySelector(".js-list"),textContentOfEmptyList:document.querySelector(".js-empty-item"),clearTasksBtn:document.querySelector(".js-clear-taskts-btn"),tasksQuantity:document.querySelector(".js-quantity"),filters:document.querySelectorAll(".js-filter-btn")};function f(t){const e=t.filter(c=>!c.completed).length,n=e===1?"task":"tasks";s.tasksQuantity.textContent=`${e} ${n} left`}function L(t){const e=t.target.closest(".js-list-item");e&&setTimeout(()=>e.classList.add("dragging"),0)}function k(t){const e=t.target.closest(".js-list-item");e&&e.classList.remove("dragging")}function b(){s.tasksListEl.addEventListener("dragstart",L),s.tasksListEl.addEventListener("dragend",k),s.tasksListEl.addEventListener("touchstart",L),s.tasksListEl.addEventListener("touchend",k)}function h(t,e){t.preventDefault();const n=s.tasksListEl.querySelector(".dragging"),c=[...s.tasksListEl.querySelectorAll(".js-list-item:not(.dragging)")],r=e?t.touches[0].clientY:t.clientY;let o=c.find(l=>r<=l.getBoundingClientRect().top+l.offsetHeight/2);s.tasksListEl.insertBefore(n,o)}function S(t){h(t,!1)}function T(t){h(t,!0)}function x(t,e){const n=document.createElement("li");return n.className="list-item js-list-item",n.id=`task-${t.id}`,n.draggable="true",n.innerHTML=`
  <input class="checkbox js-checkbox visually-hidden" type="checkbox" id="${e}"/>
  <label class="checkbox-label" for="${e}">
     <span class="custom-checkbox">
        <svg class="custom-checkbox-icon" width="10px" height="10px">
          <use href="/ToDoApp/assets/symbol-defs-BP4IDnnM.svg#icon-icon-check"></use>
        </svg>
     </span>
     <p class="task-text">${t.text}</p>
  </label>
  <button class="delate-btn" id="btn-${t.id}">
     <svg class="btn-icon">
         <use href="/ToDoApp/assets/symbol-defs-BP4IDnnM.svg#icon-icon-cross"></use>
     </svg>
  </button>
  `,n}function O(t){s.tasksListEl.innerHTML="",t.length?(s.textContentOfEmptyList.classList.add("is-hidden"),s.clearTasksBtn.disabled=!1):(s.textContentOfEmptyList.classList.remove("is-hidden"),s.clearTasksBtn.disabled=!0),t.forEach((e,n,c)=>{const r=x(e,n);s.tasksListEl.append(r);const o=r.querySelector(".js-checkbox");o.addEventListener("change",l=>{c[n].completed=l.currentTarget.checked,u("tasks",c),d(a),f(c)}),o.checked=e.completed,r.querySelector(`#btn-${e.id}`).addEventListener("click",()=>{q(e.id)})}),f(t)}function d(t){let e=[];switch(t){case"active":{e=i.filter(n=>!n.completed);break}case"completed":{e=i.filter(n=>n.completed);break}default:e=[...i]}O(e),b(),s.tasksListEl.addEventListener("dragover",S),s.tasksListEl.addEventListener("dragenter",n=>n.preventDefault()),s.tasksListEl.addEventListener("touchmove",T)}let i=g("tasks")||[],a="all";i.length&&(s.textContentOfEmptyList.classList.add("is-hidden"),d(a),s.clearTasksBtn.addEventListener("click",E));function j(t){t.preventDefault();const e=s.formEl.elements.task.value.trim();if(e==="")return;const n={id:Date.now(),text:e,completed:!1};i.push(n),d(a),s.textContentOfEmptyList.classList.add("is-hidden"),u("tasks",i),s.clearTasksBtn.addEventListener("click",E),t.currentTarget.reset()}s.formEl.addEventListener("submit",j);function E(){a==="all"?i=[]:a==="active"?i=i.filter(t=>t.completed):a==="completed"&&(i=i.filter(t=>!t.completed)),u("tasks",i),d(a),f(i),i.length||(s.textContentOfEmptyList.classList.toggle("is-hidden"),s.clearTasksBtn.disabled=!0)}function q(t){i=i.filter(e=>e.id!==t),u("tasks",i),d(a),f(i),s.tasksListEl.children.length||s.textContentOfEmptyList.classList.remove("is-hidden")}s.filters.forEach(t=>{t.addEventListener("click",e=>{document.querySelector(".js-filter-btn.active").classList.remove("active"),e.target.classList.add("active"),a=e.target.id,d(a)})});
//# sourceMappingURL=index.js.map
